QUERY_FIELDS={
  "type": "object",
  "properties": {
    "fields": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Modality",
          "BodyPartExamined",
          "StudyDescription",
          "StudyInstanceUID",
          "PatientID",
          "Program",
          "SeriesInstanceUID",
          "SOPInstanceUID",
          "SeriesDescription",
          "SliceThickness",
          "SeriesNumber",
          "StudyDate",
          "SOPClassUID",
          "collection_id",
          "AnatomicRegionSequence",
          "SegmentedPropertyCategoryCodeSequence",
          "SegmentedPropertyTypeCodeSequence",
          "FrameOfReferenceUID",
          "SegmentNumber",
          "SegmentAlgorithmType",
          "SUVbw",
          "Volume",
          "Diameter",
          "Surface_area_of",
          "Total_Lesion_Glycolysis",
          "Standardized_Added_Metabolic_Activity",
          "Percent_Within_First_Quarter_of_Intensity_Range",
          "Percent_Within_Third_Quarter_of_Intensity_Range",
          "Percent_Within_Fourth_Quarter_of_Intensity_Range",
          "Percent_Within_Second_Quarter_of_Intensity_Range",
          "Standardized_Added_Metabolic_Activity_Background",
          "Glycolysis_Within_First_Quarter_of_Intensity_Range",
          "Glycolysis_Within_Third_Quarter_of_Intensity_Range",
          "Glycolysis_Within_Fourth_Quarter_of_Intensity_Range",
          "Glycolysis_Within_Second_Quarter_of_Intensity_Range",
          "Internal_structure",
          "Sphericity",
          "Calcification",
          "Lobular_Pattern",
          "Spiculation",
          "Margin",
          "Texture",
          "Subtlety_score",
          "Malignancy",
          "Apparent_Diffusion_Coefficient",
          "tcia_species",
          "Manufacturer",
          "ManufacturerModelName",
          "license_short_name"
        ]
      }
    }
  },
  "$schema": "http://json-schema.org/schema#"
}
