from protorpc import messages

class CommonMetadataRangesItem(messages.Message):
    disease_code                                                      = messages.StringField(1, repeated=True)
    endpoint_type                                                     = messages.StringField(2, repeated=True)
    program_name                                                      = messages.StringField(3, repeated=True)
    project_short_name                                                = messages.StringField(4, repeated=True)
    
class CommonMetadataItem(messages.Message):
    disease_code                                                      = messages.StringField(1)
    endpoint_type                                                     = messages.StringField(2)
    program_name                                                      = messages.StringField(3)
    project_short_name                                                = messages.StringField(4)
    
class ClinicalMetadataRangesItem(messages.Message):
    age_at_diagnosis                                                  = messages.IntegerField(1, repeated=True, variant=messages.Variant.INT32)
    age_at_diagnosis_lte                                              = messages.IntegerField(2, variant=messages.Variant.INT32)
    age_at_diagnosis_gte                                              = messages.IntegerField(3, variant=messages.Variant.INT32)
    
    case_barcode                                                      = messages.StringField(4, repeated=True)
    days_to_birth                                                     = messages.IntegerField(5, repeated=True, variant=messages.Variant.INT32)
    days_to_birth_lte                                                 = messages.IntegerField(6, variant=messages.Variant.INT32)
    days_to_birth_gte                                                 = messages.IntegerField(7, variant=messages.Variant.INT32)
    
    days_to_death                                                     = messages.IntegerField(8, repeated=True, variant=messages.Variant.INT32)
    days_to_death_lte                                                 = messages.IntegerField(9, variant=messages.Variant.INT32)
    days_to_death_gte                                                 = messages.IntegerField(10, variant=messages.Variant.INT32)
    
    days_to_last_followup                                             = messages.IntegerField(11, repeated=True, variant=messages.Variant.INT32)
    days_to_last_followup_lte                                         = messages.IntegerField(12, variant=messages.Variant.INT32)
    days_to_last_followup_gte                                         = messages.IntegerField(13, variant=messages.Variant.INT32)
    
    days_to_last_known_alive                                          = messages.IntegerField(14, repeated=True, variant=messages.Variant.INT32)
    days_to_last_known_alive_lte                                      = messages.IntegerField(15, variant=messages.Variant.INT32)
    days_to_last_known_alive_gte                                      = messages.IntegerField(16, variant=messages.Variant.INT32)
    
    ethnicity                                                         = messages.StringField(17, repeated=True)
    event_free_survival                                               = messages.IntegerField(18, repeated=True, variant=messages.Variant.INT32)
    event_free_survival_lte                                           = messages.IntegerField(19, variant=messages.Variant.INT32)
    event_free_survival_gte                                           = messages.IntegerField(20, variant=messages.Variant.INT32)
    
    first_event                                                       = messages.StringField(21, repeated=True)
    gender                                                            = messages.StringField(22, repeated=True)
    overall_survival                                                  = messages.IntegerField(23, repeated=True, variant=messages.Variant.INT32)
    overall_survival_lte                                              = messages.IntegerField(24, variant=messages.Variant.INT32)
    overall_survival_gte                                              = messages.IntegerField(25, variant=messages.Variant.INT32)
    
    protocol                                                          = messages.StringField(26, repeated=True)
    race                                                              = messages.StringField(27, repeated=True)
    summary_file_count                                                = messages.IntegerField(28, repeated=True, variant=messages.Variant.INT32)
    summary_file_count_lte                                            = messages.IntegerField(29, variant=messages.Variant.INT32)
    summary_file_count_gte                                            = messages.IntegerField(30, variant=messages.Variant.INT32)
    
    vital_status                                                      = messages.StringField(31, repeated=True)
    wbc_at_diagnosis                                                  = messages.FloatField(32, repeated=True)
    wbc_at_diagnosis_lte                                              = messages.FloatField(33)
    wbc_at_diagnosis_gte                                              = messages.FloatField(34)
    
    year_of_diagnosis                                                 = messages.IntegerField(35, repeated=True, variant=messages.Variant.INT32)
    year_of_diagnosis_lte                                             = messages.IntegerField(36, variant=messages.Variant.INT32)
    year_of_diagnosis_gte                                             = messages.IntegerField(37, variant=messages.Variant.INT32)
    
    year_of_last_follow_up                                            = messages.IntegerField(38, repeated=True, variant=messages.Variant.INT32)
    year_of_last_follow_up_lte                                        = messages.IntegerField(39, variant=messages.Variant.INT32)
    year_of_last_follow_up_gte                                        = messages.IntegerField(40, variant=messages.Variant.INT32)
    
    
class ClinicalMetadataItem(messages.Message):
    age_at_diagnosis                                                  = messages.IntegerField(1, variant=messages.Variant.INT32)
    case_barcode                                                      = messages.StringField(2)
    days_to_birth                                                     = messages.IntegerField(3, variant=messages.Variant.INT32)
    days_to_death                                                     = messages.IntegerField(4, variant=messages.Variant.INT32)
    days_to_last_followup                                             = messages.IntegerField(5, variant=messages.Variant.INT32)
    days_to_last_known_alive                                          = messages.IntegerField(6, variant=messages.Variant.INT32)
    ethnicity                                                         = messages.StringField(7)
    event_free_survival                                               = messages.IntegerField(8, variant=messages.Variant.INT32)
    first_event                                                       = messages.StringField(9)
    gender                                                            = messages.StringField(10)
    overall_survival                                                  = messages.IntegerField(11, variant=messages.Variant.INT32)
    protocol                                                          = messages.StringField(12)
    race                                                              = messages.StringField(13)
    summary_file_count                                                = messages.IntegerField(14, variant=messages.Variant.INT32)
    vital_status                                                      = messages.StringField(15)
    wbc_at_diagnosis                                                  = messages.FloatField(16)
    year_of_diagnosis                                                 = messages.IntegerField(17, variant=messages.Variant.INT32)
    year_of_last_follow_up                                            = messages.IntegerField(18, variant=messages.Variant.INT32)
    
class BiospecimenMetadataRangesItem(messages.Message):
    case_barcode                                                      = messages.StringField(1, repeated=True)
    sample_barcode                                                    = messages.StringField(2, repeated=True)
    sample_type                                                       = messages.StringField(3, repeated=True)
    tumor_code                                                        = messages.StringField(4, repeated=True)
    
class BiospecimenMetadataItem(messages.Message):
    case_barcode                                                      = messages.StringField(1)
    sample_barcode                                                    = messages.StringField(2)
    sample_type                                                       = messages.StringField(3)
    tumor_code                                                        = messages.StringField(4)
    
class Data_HG19MetadataRangesItem(messages.Message):
    access                                                            = messages.StringField(1, repeated=True)
    aliquot_barcode                                                   = messages.StringField(2, repeated=True)
    analysis_workflow_type                                            = messages.StringField(3, repeated=True)
    case_barcode                                                      = messages.StringField(4, repeated=True)
    center_code                                                       = messages.StringField(5, repeated=True)
    center_name                                                       = messages.StringField(6, repeated=True)
    center_type                                                       = messages.StringField(7, repeated=True)
    data_category                                                     = messages.StringField(8, repeated=True)
    data_format                                                       = messages.StringField(9, repeated=True)
    data_type                                                         = messages.StringField(10, repeated=True)
    experimental_strategy                                             = messages.StringField(11, repeated=True)
    file_name                                                         = messages.StringField(12, repeated=True)
    file_state                                                        = messages.StringField(13, repeated=True)
    file_uploaded                                                     = messages.StringField(14, repeated=True)
    index_file_name                                                   = messages.StringField(15, repeated=True)
    platform                                                          = messages.StringField(16, repeated=True)
    sample_barcode                                                    = messages.StringField(17, repeated=True)
    sample_type                                                       = messages.StringField(18, repeated=True)
    species                                                           = messages.StringField(19, repeated=True)
    
class Data_HG19MetadataItem(messages.Message):
    access                                                            = messages.StringField(1)
    aliquot_barcode                                                   = messages.StringField(2)
    analysis_workflow_type                                            = messages.StringField(3)
    case_barcode                                                      = messages.StringField(4)
    center_code                                                       = messages.StringField(5)
    center_name                                                       = messages.StringField(6)
    center_type                                                       = messages.StringField(7)
    data_category                                                     = messages.StringField(8)
    data_format                                                       = messages.StringField(9)
    data_type                                                         = messages.StringField(10)
    experimental_strategy                                             = messages.StringField(11)
    file_name                                                         = messages.StringField(12)
    file_state                                                        = messages.StringField(13)
    file_uploaded                                                     = messages.StringField(14)
    index_file_name                                                   = messages.StringField(15)
    platform                                                          = messages.StringField(16)
    sample_barcode                                                    = messages.StringField(17)
    sample_type                                                       = messages.StringField(18)
    species                                                           = messages.StringField(19)
    
class Data_HG38MetadataRangesItem(messages.Message):
    access                                                            = messages.StringField(1, repeated=True)
    aliquot_barcode                                                   = messages.StringField(2, repeated=True)
    analysis_workflow_type                                            = messages.StringField(3, repeated=True)
    case_barcode                                                      = messages.StringField(4, repeated=True)
    center_code                                                       = messages.StringField(5, repeated=True)
    center_name                                                       = messages.StringField(6, repeated=True)
    center_type                                                       = messages.StringField(7, repeated=True)
    data_category                                                     = messages.StringField(8, repeated=True)
    data_format                                                       = messages.StringField(9, repeated=True)
    data_type                                                         = messages.StringField(10, repeated=True)
    experimental_strategy                                             = messages.StringField(11, repeated=True)
    file_name                                                         = messages.StringField(12, repeated=True)
    file_state                                                        = messages.StringField(13, repeated=True)
    file_uploaded                                                     = messages.StringField(14, repeated=True)
    index_file_name                                                   = messages.StringField(15, repeated=True)
    platform                                                          = messages.StringField(16, repeated=True)
    sample_barcode                                                    = messages.StringField(17, repeated=True)
    sample_type                                                       = messages.StringField(18, repeated=True)
    species                                                           = messages.StringField(19, repeated=True)
    
class Data_HG38MetadataItem(messages.Message):
    access                                                            = messages.StringField(1)
    aliquot_barcode                                                   = messages.StringField(2)
    analysis_workflow_type                                            = messages.StringField(3)
    case_barcode                                                      = messages.StringField(4)
    center_code                                                       = messages.StringField(5)
    center_name                                                       = messages.StringField(6)
    center_type                                                       = messages.StringField(7)
    data_category                                                     = messages.StringField(8)
    data_format                                                       = messages.StringField(9)
    data_type                                                         = messages.StringField(10)
    experimental_strategy                                             = messages.StringField(11)
    file_name                                                         = messages.StringField(12)
    file_state                                                        = messages.StringField(13)
    file_uploaded                                                     = messages.StringField(14)
    index_file_name                                                   = messages.StringField(15)
    platform                                                          = messages.StringField(16)
    sample_barcode                                                    = messages.StringField(17)
    sample_type                                                       = messages.StringField(18)
    species                                                           = messages.StringField(19)
    
class MetadataRangesItem(messages.Message):
    Common = messages.MessageField(CommonMetadataRangesItem, 1)
    Clinical = messages.MessageField(ClinicalMetadataRangesItem, 2)
    Biospecimen = messages.MessageField(BiospecimenMetadataRangesItem, 3)
    Data_HG19 = messages.MessageField(Data_HG19MetadataRangesItem, 4)
    Data_HG38 = messages.MessageField(Data_HG38MetadataRangesItem, 5)

class MetadataItem(messages.Message):
    Common = messages.MessageField(CommonMetadataItem, 1)
    Clinical = messages.MessageField(ClinicalMetadataItem, 2)
    Biospecimen = messages.MessageField(BiospecimenMetadataItem, 3)
    Data_HG19 = messages.MessageField(Data_HG19MetadataItem, 4)
    Data_HG38 = messages.MessageField(Data_HG38MetadataItem, 5)

