QUERY_FIELDS={
  "type": "object",
  "properties": {
    "fields": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Apparent_Diffusion_Coefficient",
          "tcia_species",
          "Modality",
          "tcia_tumorLocation",
          "AnatomicRegionSequence",
          "SegmentedPropertyCategoryCodeSequence",
          "SegmentedPropertyTypeCodeSequence",
          "Volume",
          "Diameter",
          "Surface_area_of_mesh",
          "Internal_structure",
          "Sphericity",
          "Calcification",
          "Lobular_Pattern",
          "Spiculation",
          "Margin",
          "Texture",
          "Subtlety_score",
          "Malignancy",
          "BodyPartExamined",
          "SOPClassUID",
          "collection_id",
          "StudyDescription",
          "StudyInstanceUID",
          "PatientID",
          "SeriesInstanceUID",
          "SOPInstanceUID",
          "SeriesDescription",
          "SliceThickness",
          "SeriesNumber",
          "StudyDate",
          "Manufacturer",
          "ManufacturerModelName",
          "license_short_name",
          "analysis_results_id",
          "SamplesPerPixel",
          "Volume_of_Mesh",
          "Sphericity_quant",
          "illuminationType",
          "primaryAnatomicStructure",
          "ObjectiveLensPower",
          "min_PixelSpacing",
          "max_TotalPixelMatrixColumns",
          "max_TotalPixelMatrixRows",
          "CancerType",
          "counts",
          "sizes"
        ]
      }
    }
  },
  "$schema": "http://json-schema.org/schema#"
}