from protorpc import messages

class CommonMetadataRangesItem(messages.Message):
    disease_code                                                      = messages.StringField(1, repeated=True)
    endpoint_type                                                     = messages.StringField(2, repeated=True)
    program_name                                                      = messages.StringField(3, repeated=True)
    project_short_name                                                = messages.StringField(4, repeated=True)
    
class CommonMetadataItem(messages.Message):
    disease_code                                                      = messages.StringField(1)
    endpoint_type                                                     = messages.StringField(2)
    program_name                                                      = messages.StringField(3)
    project_short_name                                                = messages.StringField(4)
    
class ClinicalMetadataRangesItem(messages.Message):
    age_at_diagnosis                                                  = messages.IntegerField(1, repeated=True, variant=messages.Variant.INT32)
    age_at_diagnosis_lte                                              = messages.IntegerField(2, variant=messages.Variant.INT32)
    age_at_diagnosis_gte                                              = messages.IntegerField(3, variant=messages.Variant.INT32)
    
    age_began_smoking_in_years                                        = messages.IntegerField(4, repeated=True, variant=messages.Variant.INT32)
    age_began_smoking_in_years_lte                                    = messages.IntegerField(5, variant=messages.Variant.INT32)
    age_began_smoking_in_years_gte                                    = messages.IntegerField(6, variant=messages.Variant.INT32)
    
    anatomic_neoplasm_subdivision                                     = messages.StringField(7, repeated=True)
    batch_number                                                      = messages.IntegerField(8, repeated=True, variant=messages.Variant.INT32)
    batch_number_lte                                                  = messages.IntegerField(9, variant=messages.Variant.INT32)
    batch_number_gte                                                  = messages.IntegerField(10, variant=messages.Variant.INT32)
    
    bcr                                                               = messages.StringField(11, repeated=True)
    bmi                                                               = messages.FloatField(12, repeated=True)
    bmi_lte                                                           = messages.FloatField(13)
    bmi_gte                                                           = messages.FloatField(14)
    
    case_barcode                                                      = messages.StringField(15, repeated=True)
    case_gdc_id                                                       = messages.StringField(16, repeated=True)
    clinical_M                                                        = messages.StringField(17, repeated=True)
    clinical_N                                                        = messages.StringField(18, repeated=True)
    clinical_stage                                                    = messages.StringField(19, repeated=True)
    clinical_T                                                        = messages.StringField(20, repeated=True)
    colorectal_cancer                                                 = messages.StringField(21, repeated=True)
    country                                                           = messages.StringField(22, repeated=True)
    days_to_birth                                                     = messages.IntegerField(23, repeated=True, variant=messages.Variant.INT32)
    days_to_birth_lte                                                 = messages.IntegerField(24, variant=messages.Variant.INT32)
    days_to_birth_gte                                                 = messages.IntegerField(25, variant=messages.Variant.INT32)
    
    days_to_death                                                     = messages.IntegerField(26, repeated=True, variant=messages.Variant.INT32)
    days_to_death_lte                                                 = messages.IntegerField(27, variant=messages.Variant.INT32)
    days_to_death_gte                                                 = messages.IntegerField(28, variant=messages.Variant.INT32)
    
    days_to_initial_pathologic_diagnosis                              = messages.IntegerField(29, repeated=True, variant=messages.Variant.INT32)
    days_to_initial_pathologic_diagnosis_lte                          = messages.IntegerField(30, variant=messages.Variant.INT32)
    days_to_initial_pathologic_diagnosis_gte                          = messages.IntegerField(31, variant=messages.Variant.INT32)
    
    days_to_last_followup                                             = messages.IntegerField(32, repeated=True, variant=messages.Variant.INT32)
    days_to_last_followup_lte                                         = messages.IntegerField(33, variant=messages.Variant.INT32)
    days_to_last_followup_gte                                         = messages.IntegerField(34, variant=messages.Variant.INT32)
    
    days_to_last_known_alive                                          = messages.IntegerField(35, repeated=True, variant=messages.Variant.INT32)
    days_to_last_known_alive_lte                                      = messages.IntegerField(36, variant=messages.Variant.INT32)
    days_to_last_known_alive_gte                                      = messages.IntegerField(37, variant=messages.Variant.INT32)
    
    days_to_submitted_specimen_dx                                     = messages.IntegerField(38, repeated=True, variant=messages.Variant.INT32)
    days_to_submitted_specimen_dx_lte                                 = messages.IntegerField(39, variant=messages.Variant.INT32)
    days_to_submitted_specimen_dx_gte                                 = messages.IntegerField(40, variant=messages.Variant.INT32)
    
    ethnicity                                                         = messages.StringField(41, repeated=True)
    gender                                                            = messages.StringField(42, repeated=True)
    gleason_score_combined                                            = messages.IntegerField(43, repeated=True, variant=messages.Variant.INT32)
    gleason_score_combined_lte                                        = messages.IntegerField(44, variant=messages.Variant.INT32)
    gleason_score_combined_gte                                        = messages.IntegerField(45, variant=messages.Variant.INT32)
    
    height                                                            = messages.IntegerField(46, repeated=True, variant=messages.Variant.INT32)
    height_lte                                                        = messages.IntegerField(47, variant=messages.Variant.INT32)
    height_gte                                                        = messages.IntegerField(48, variant=messages.Variant.INT32)
    
    histological_type                                                 = messages.StringField(49, repeated=True)
    history_of_colon_polyps                                           = messages.StringField(50, repeated=True)
    history_of_neoadjuvant_treatment                                  = messages.StringField(51, repeated=True)
    hpv_calls                                                         = messages.StringField(52, repeated=True)
    hpv_status                                                        = messages.StringField(53, repeated=True)
    h_pylori_infection                                                = messages.StringField(54, repeated=True)
    icd_10                                                            = messages.StringField(55, repeated=True)
    icd_o_3_histology                                                 = messages.StringField(56, repeated=True)
    icd_o_3_site                                                      = messages.StringField(57, repeated=True)
    lymphatic_invasion                                                = messages.StringField(58, repeated=True)
    lymphnodes_examined                                               = messages.StringField(59, repeated=True)
    lymphovascular_invasion_present                                   = messages.StringField(60, repeated=True)
    menopause_status                                                  = messages.StringField(61, repeated=True)
    mononucleotide_and_dinucleotide_marker_panel_analysis_status      = messages.StringField(62, repeated=True)
    neoplasm_histologic_grade                                         = messages.StringField(63, repeated=True)
    new_tumor_event_after_initial_treatment                           = messages.StringField(64, repeated=True)
    number_of_lymphnodes_examined                                     = messages.IntegerField(65, repeated=True, variant=messages.Variant.INT32)
    number_of_lymphnodes_examined_lte                                 = messages.IntegerField(66, variant=messages.Variant.INT32)
    number_of_lymphnodes_examined_gte                                 = messages.IntegerField(67, variant=messages.Variant.INT32)
    
    number_of_lymphnodes_positive_by_he                               = messages.IntegerField(68, repeated=True, variant=messages.Variant.INT32)
    number_of_lymphnodes_positive_by_he_lte                           = messages.IntegerField(69, variant=messages.Variant.INT32)
    number_of_lymphnodes_positive_by_he_gte                           = messages.IntegerField(70, variant=messages.Variant.INT32)
    
    number_pack_years_smoked                                          = messages.IntegerField(71, repeated=True, variant=messages.Variant.INT32)
    number_pack_years_smoked_lte                                      = messages.IntegerField(72, variant=messages.Variant.INT32)
    number_pack_years_smoked_gte                                      = messages.IntegerField(73, variant=messages.Variant.INT32)
    
    other_dx                                                          = messages.StringField(74, repeated=True)
    other_malignancy_anatomic_site                                    = messages.StringField(75, repeated=True)
    other_malignancy_histological_type                                = messages.StringField(76, repeated=True)
    other_malignancy_type                                             = messages.StringField(77, repeated=True)
    pathologic_M                                                      = messages.StringField(78, repeated=True)
    pathologic_N                                                      = messages.StringField(79, repeated=True)
    pathologic_stage                                                  = messages.StringField(80, repeated=True)
    pathologic_T                                                      = messages.StringField(81, repeated=True)
    person_neoplasm_cancer_status                                     = messages.StringField(82, repeated=True)
    pregnancies                                                       = messages.StringField(83, repeated=True)
    primary_neoplasm_melanoma_dx                                      = messages.StringField(84, repeated=True)
    primary_therapy_outcome_success                                   = messages.StringField(85, repeated=True)
    psa_value                                                         = messages.FloatField(86, repeated=True)
    psa_value_lte                                                     = messages.FloatField(87)
    psa_value_gte                                                     = messages.FloatField(88)
    
    race                                                              = messages.StringField(89, repeated=True)
    residual_tumor                                                    = messages.StringField(90, repeated=True)
    stopped_smoking_year                                              = messages.IntegerField(91, repeated=True, variant=messages.Variant.INT32)
    stopped_smoking_year_lte                                          = messages.IntegerField(92, variant=messages.Variant.INT32)
    stopped_smoking_year_gte                                          = messages.IntegerField(93, variant=messages.Variant.INT32)
    
    summary_file_count                                                = messages.IntegerField(94, repeated=True, variant=messages.Variant.INT32)
    summary_file_count_lte                                            = messages.IntegerField(95, variant=messages.Variant.INT32)
    summary_file_count_gte                                            = messages.IntegerField(96, variant=messages.Variant.INT32)
    
    tobacco_smoking_history                                           = messages.StringField(97, repeated=True)
    tss_code                                                          = messages.StringField(98, repeated=True)
    tumor_tissue_site                                                 = messages.StringField(99, repeated=True)
    tumor_type                                                        = messages.StringField(100, repeated=True)
    venous_invasion                                                   = messages.StringField(101, repeated=True)
    vital_status                                                      = messages.StringField(102, repeated=True)
    weight                                                            = messages.IntegerField(103, repeated=True, variant=messages.Variant.INT32)
    weight_lte                                                        = messages.IntegerField(104, variant=messages.Variant.INT32)
    weight_gte                                                        = messages.IntegerField(105, variant=messages.Variant.INT32)
    
    year_of_diagnosis                                                 = messages.IntegerField(106, repeated=True, variant=messages.Variant.INT32)
    year_of_diagnosis_lte                                             = messages.IntegerField(107, variant=messages.Variant.INT32)
    year_of_diagnosis_gte                                             = messages.IntegerField(108, variant=messages.Variant.INT32)
    
    year_of_tobacco_smoking_onset                                     = messages.IntegerField(109, repeated=True, variant=messages.Variant.INT32)
    year_of_tobacco_smoking_onset_lte                                 = messages.IntegerField(110, variant=messages.Variant.INT32)
    year_of_tobacco_smoking_onset_gte                                 = messages.IntegerField(111, variant=messages.Variant.INT32)
    
    
class ClinicalMetadataItem(messages.Message):
    age_at_diagnosis                                                  = messages.IntegerField(1, variant=messages.Variant.INT32)
    age_began_smoking_in_years                                        = messages.IntegerField(2, variant=messages.Variant.INT32)
    anatomic_neoplasm_subdivision                                     = messages.StringField(3)
    batch_number                                                      = messages.IntegerField(4, variant=messages.Variant.INT32)
    bcr                                                               = messages.StringField(5)
    bmi                                                               = messages.FloatField(6)
    case_barcode                                                      = messages.StringField(7)
    case_gdc_id                                                       = messages.StringField(8)
    clinical_M                                                        = messages.StringField(9)
    clinical_N                                                        = messages.StringField(10)
    clinical_stage                                                    = messages.StringField(11)
    clinical_T                                                        = messages.StringField(12)
    colorectal_cancer                                                 = messages.StringField(13)
    country                                                           = messages.StringField(14)
    days_to_birth                                                     = messages.IntegerField(15, variant=messages.Variant.INT32)
    days_to_death                                                     = messages.IntegerField(16, variant=messages.Variant.INT32)
    days_to_initial_pathologic_diagnosis                              = messages.IntegerField(17, variant=messages.Variant.INT32)
    days_to_last_followup                                             = messages.IntegerField(18, variant=messages.Variant.INT32)
    days_to_last_known_alive                                          = messages.IntegerField(19, variant=messages.Variant.INT32)
    days_to_submitted_specimen_dx                                     = messages.IntegerField(20, variant=messages.Variant.INT32)
    ethnicity                                                         = messages.StringField(21)
    gender                                                            = messages.StringField(22)
    gleason_score_combined                                            = messages.IntegerField(23, variant=messages.Variant.INT32)
    height                                                            = messages.IntegerField(24, variant=messages.Variant.INT32)
    histological_type                                                 = messages.StringField(25)
    history_of_colon_polyps                                           = messages.StringField(26)
    history_of_neoadjuvant_treatment                                  = messages.StringField(27)
    hpv_calls                                                         = messages.StringField(28)
    hpv_status                                                        = messages.StringField(29)
    h_pylori_infection                                                = messages.StringField(30)
    icd_10                                                            = messages.StringField(31)
    icd_o_3_histology                                                 = messages.StringField(32)
    icd_o_3_site                                                      = messages.StringField(33)
    lymphatic_invasion                                                = messages.StringField(34)
    lymphnodes_examined                                               = messages.StringField(35)
    lymphovascular_invasion_present                                   = messages.StringField(36)
    menopause_status                                                  = messages.StringField(37)
    mononucleotide_and_dinucleotide_marker_panel_analysis_status      = messages.StringField(38)
    neoplasm_histologic_grade                                         = messages.StringField(39)
    new_tumor_event_after_initial_treatment                           = messages.StringField(40)
    number_of_lymphnodes_examined                                     = messages.IntegerField(41, variant=messages.Variant.INT32)
    number_of_lymphnodes_positive_by_he                               = messages.IntegerField(42, variant=messages.Variant.INT32)
    number_pack_years_smoked                                          = messages.IntegerField(43, variant=messages.Variant.INT32)
    other_dx                                                          = messages.StringField(44)
    other_malignancy_anatomic_site                                    = messages.StringField(45)
    other_malignancy_histological_type                                = messages.StringField(46)
    other_malignancy_type                                             = messages.StringField(47)
    pathologic_M                                                      = messages.StringField(48)
    pathologic_N                                                      = messages.StringField(49)
    pathologic_stage                                                  = messages.StringField(50)
    pathologic_T                                                      = messages.StringField(51)
    person_neoplasm_cancer_status                                     = messages.StringField(52)
    pregnancies                                                       = messages.StringField(53)
    primary_neoplasm_melanoma_dx                                      = messages.StringField(54)
    primary_therapy_outcome_success                                   = messages.StringField(55)
    psa_value                                                         = messages.FloatField(56)
    race                                                              = messages.StringField(57)
    residual_tumor                                                    = messages.StringField(58)
    stopped_smoking_year                                              = messages.IntegerField(59, variant=messages.Variant.INT32)
    summary_file_count                                                = messages.IntegerField(60, variant=messages.Variant.INT32)
    tobacco_smoking_history                                           = messages.StringField(61)
    tss_code                                                          = messages.StringField(62)
    tumor_tissue_site                                                 = messages.StringField(63)
    tumor_type                                                        = messages.StringField(64)
    venous_invasion                                                   = messages.StringField(65)
    vital_status                                                      = messages.StringField(66)
    weight                                                            = messages.IntegerField(67, variant=messages.Variant.INT32)
    year_of_diagnosis                                                 = messages.IntegerField(68, variant=messages.Variant.INT32)
    year_of_tobacco_smoking_onset                                     = messages.IntegerField(69, variant=messages.Variant.INT32)
    
class BiospecimenMetadataRangesItem(messages.Message):
    avg_percent_lymphocyte_infiltration                               = messages.FloatField(1, repeated=True)
    avg_percent_lymphocyte_infiltration_lte                           = messages.FloatField(2)
    avg_percent_lymphocyte_infiltration_gte                           = messages.FloatField(3)
    
    avg_percent_monocyte_infiltration                                 = messages.FloatField(4, repeated=True)
    avg_percent_monocyte_infiltration_lte                             = messages.FloatField(5)
    avg_percent_monocyte_infiltration_gte                             = messages.FloatField(6)
    
    avg_percent_necrosis                                              = messages.FloatField(7, repeated=True)
    avg_percent_necrosis_lte                                          = messages.FloatField(8)
    avg_percent_necrosis_gte                                          = messages.FloatField(9)
    
    avg_percent_neutrophil_infiltration                               = messages.FloatField(10, repeated=True)
    avg_percent_neutrophil_infiltration_lte                           = messages.FloatField(11)
    avg_percent_neutrophil_infiltration_gte                           = messages.FloatField(12)
    
    avg_percent_normal_cells                                          = messages.FloatField(13, repeated=True)
    avg_percent_normal_cells_lte                                      = messages.FloatField(14)
    avg_percent_normal_cells_gte                                      = messages.FloatField(15)
    
    avg_percent_stromal_cells                                         = messages.FloatField(16, repeated=True)
    avg_percent_stromal_cells_lte                                     = messages.FloatField(17)
    avg_percent_stromal_cells_gte                                     = messages.FloatField(18)
    
    avg_percent_tumor_cells                                           = messages.FloatField(19, repeated=True)
    avg_percent_tumor_cells_lte                                       = messages.FloatField(20)
    avg_percent_tumor_cells_gte                                       = messages.FloatField(21)
    
    avg_percent_tumor_nuclei                                          = messages.FloatField(22, repeated=True)
    avg_percent_tumor_nuclei_lte                                      = messages.FloatField(23)
    avg_percent_tumor_nuclei_gte                                      = messages.FloatField(24)
    
    batch_number                                                      = messages.IntegerField(25, repeated=True, variant=messages.Variant.INT32)
    batch_number_lte                                                  = messages.IntegerField(26, variant=messages.Variant.INT32)
    batch_number_gte                                                  = messages.IntegerField(27, variant=messages.Variant.INT32)
    
    bcr                                                               = messages.StringField(28, repeated=True)
    case_barcode                                                      = messages.StringField(29, repeated=True)
    case_gdc_id                                                       = messages.StringField(30, repeated=True)
    days_to_collection                                                = messages.IntegerField(31, repeated=True, variant=messages.Variant.INT32)
    days_to_collection_lte                                            = messages.IntegerField(32, variant=messages.Variant.INT32)
    days_to_collection_gte                                            = messages.IntegerField(33, variant=messages.Variant.INT32)
    
    days_to_sample_procurement                                        = messages.IntegerField(34, repeated=True, variant=messages.Variant.INT32)
    days_to_sample_procurement_lte                                    = messages.IntegerField(35, variant=messages.Variant.INT32)
    days_to_sample_procurement_gte                                    = messages.IntegerField(36, variant=messages.Variant.INT32)
    
    max_percent_lymphocyte_infiltration                               = messages.FloatField(37, repeated=True)
    max_percent_lymphocyte_infiltration_lte                           = messages.FloatField(38)
    max_percent_lymphocyte_infiltration_gte                           = messages.FloatField(39)
    
    max_percent_monocyte_infiltration                                 = messages.FloatField(40, repeated=True)
    max_percent_monocyte_infiltration_lte                             = messages.FloatField(41)
    max_percent_monocyte_infiltration_gte                             = messages.FloatField(42)
    
    max_percent_necrosis                                              = messages.FloatField(43, repeated=True)
    max_percent_necrosis_lte                                          = messages.FloatField(44)
    max_percent_necrosis_gte                                          = messages.FloatField(45)
    
    max_percent_neutrophil_infiltration                               = messages.FloatField(46, repeated=True)
    max_percent_neutrophil_infiltration_lte                           = messages.FloatField(47)
    max_percent_neutrophil_infiltration_gte                           = messages.FloatField(48)
    
    max_percent_normal_cells                                          = messages.FloatField(49, repeated=True)
    max_percent_normal_cells_lte                                      = messages.FloatField(50)
    max_percent_normal_cells_gte                                      = messages.FloatField(51)
    
    max_percent_stromal_cells                                         = messages.FloatField(52, repeated=True)
    max_percent_stromal_cells_lte                                     = messages.FloatField(53)
    max_percent_stromal_cells_gte                                     = messages.FloatField(54)
    
    max_percent_tumor_cells                                           = messages.FloatField(55, repeated=True)
    max_percent_tumor_cells_lte                                       = messages.FloatField(56)
    max_percent_tumor_cells_gte                                       = messages.FloatField(57)
    
    max_percent_tumor_nuclei                                          = messages.FloatField(58, repeated=True)
    max_percent_tumor_nuclei_lte                                      = messages.FloatField(59)
    max_percent_tumor_nuclei_gte                                      = messages.FloatField(60)
    
    min_percent_lymphocyte_infiltration                               = messages.FloatField(61, repeated=True)
    min_percent_lymphocyte_infiltration_lte                           = messages.FloatField(62)
    min_percent_lymphocyte_infiltration_gte                           = messages.FloatField(63)
    
    min_percent_monocyte_infiltration                                 = messages.FloatField(64, repeated=True)
    min_percent_monocyte_infiltration_lte                             = messages.FloatField(65)
    min_percent_monocyte_infiltration_gte                             = messages.FloatField(66)
    
    min_percent_necrosis                                              = messages.FloatField(67, repeated=True)
    min_percent_necrosis_lte                                          = messages.FloatField(68)
    min_percent_necrosis_gte                                          = messages.FloatField(69)
    
    min_percent_neutrophil_infiltration                               = messages.FloatField(70, repeated=True)
    min_percent_neutrophil_infiltration_lte                           = messages.FloatField(71)
    min_percent_neutrophil_infiltration_gte                           = messages.FloatField(72)
    
    min_percent_normal_cells                                          = messages.FloatField(73, repeated=True)
    min_percent_normal_cells_lte                                      = messages.FloatField(74)
    min_percent_normal_cells_gte                                      = messages.FloatField(75)
    
    min_percent_stromal_cells                                         = messages.FloatField(76, repeated=True)
    min_percent_stromal_cells_lte                                     = messages.FloatField(77)
    min_percent_stromal_cells_gte                                     = messages.FloatField(78)
    
    min_percent_tumor_cells                                           = messages.FloatField(79, repeated=True)
    min_percent_tumor_cells_lte                                       = messages.FloatField(80)
    min_percent_tumor_cells_gte                                       = messages.FloatField(81)
    
    min_percent_tumor_nuclei                                          = messages.FloatField(82, repeated=True)
    min_percent_tumor_nuclei_lte                                      = messages.FloatField(83)
    min_percent_tumor_nuclei_gte                                      = messages.FloatField(84)
    
    num_portions                                                      = messages.IntegerField(85, repeated=True, variant=messages.Variant.INT32)
    num_portions_lte                                                  = messages.IntegerField(86, variant=messages.Variant.INT32)
    num_portions_gte                                                  = messages.IntegerField(87, variant=messages.Variant.INT32)
    
    num_slides                                                        = messages.IntegerField(88, repeated=True, variant=messages.Variant.INT32)
    num_slides_lte                                                    = messages.IntegerField(89, variant=messages.Variant.INT32)
    num_slides_gte                                                    = messages.IntegerField(90, variant=messages.Variant.INT32)
    
    pathology_report_uuid                                             = messages.StringField(91, repeated=True)
    preservation_method                                               = messages.StringField(92, repeated=True)
    sample_barcode                                                    = messages.StringField(93, repeated=True)
    sample_gdc_id                                                     = messages.StringField(94, repeated=True)
    sample_type                                                       = messages.StringField(95, repeated=True)
    
class BiospecimenMetadataItem(messages.Message):
    avg_percent_lymphocyte_infiltration                               = messages.FloatField(1)
    avg_percent_monocyte_infiltration                                 = messages.FloatField(2)
    avg_percent_necrosis                                              = messages.FloatField(3)
    avg_percent_neutrophil_infiltration                               = messages.FloatField(4)
    avg_percent_normal_cells                                          = messages.FloatField(5)
    avg_percent_stromal_cells                                         = messages.FloatField(6)
    avg_percent_tumor_cells                                           = messages.FloatField(7)
    avg_percent_tumor_nuclei                                          = messages.FloatField(8)
    batch_number                                                      = messages.IntegerField(9, variant=messages.Variant.INT32)
    bcr                                                               = messages.StringField(10)
    case_barcode                                                      = messages.StringField(11)
    case_gdc_id                                                       = messages.StringField(12)
    days_to_collection                                                = messages.IntegerField(13, variant=messages.Variant.INT32)
    days_to_sample_procurement                                        = messages.IntegerField(14, variant=messages.Variant.INT32)
    max_percent_lymphocyte_infiltration                               = messages.FloatField(15)
    max_percent_monocyte_infiltration                                 = messages.FloatField(16)
    max_percent_necrosis                                              = messages.FloatField(17)
    max_percent_neutrophil_infiltration                               = messages.FloatField(18)
    max_percent_normal_cells                                          = messages.FloatField(19)
    max_percent_stromal_cells                                         = messages.FloatField(20)
    max_percent_tumor_cells                                           = messages.FloatField(21)
    max_percent_tumor_nuclei                                          = messages.FloatField(22)
    min_percent_lymphocyte_infiltration                               = messages.FloatField(23)
    min_percent_monocyte_infiltration                                 = messages.FloatField(24)
    min_percent_necrosis                                              = messages.FloatField(25)
    min_percent_neutrophil_infiltration                               = messages.FloatField(26)
    min_percent_normal_cells                                          = messages.FloatField(27)
    min_percent_stromal_cells                                         = messages.FloatField(28)
    min_percent_tumor_cells                                           = messages.FloatField(29)
    min_percent_tumor_nuclei                                          = messages.FloatField(30)
    num_portions                                                      = messages.IntegerField(31, variant=messages.Variant.INT32)
    num_slides                                                        = messages.IntegerField(32, variant=messages.Variant.INT32)
    pathology_report_uuid                                             = messages.StringField(33)
    preservation_method                                               = messages.StringField(34)
    sample_barcode                                                    = messages.StringField(35)
    sample_gdc_id                                                     = messages.StringField(36)
    sample_type                                                       = messages.StringField(37)
    
class Data_HG19MetadataRangesItem(messages.Message):
    access                                                            = messages.StringField(1, repeated=True)
    case_barcode                                                      = messages.StringField(7, repeated=True)
    case_gdc_id                                                       = messages.StringField(8, repeated=True)
    data_category                                                     = messages.StringField(12, repeated=True)
    data_format                                                       = messages.StringField(13, repeated=True)
    data_type                                                         = messages.StringField(14, repeated=True)
    experimental_strategy                                             = messages.StringField(15, repeated=True)
    index_file_name_key                                               = messages.StringField(19, repeated=True)
    file_name_key                                                     = messages.StringField(18, repeated=True)
    platform                                                          = messages.StringField(20, repeated=True)
    sample_barcode                                                    = messages.StringField(21, repeated=True)
    sample_gdc_id                                                     = messages.StringField(22, repeated=True)
    sample_type                                                       = messages.StringField(23, repeated=True)
    
class Data_HG19MetadataItem(messages.Message):
    access                                                            = messages.StringField(1)
    case_barcode                                                      = messages.StringField(7)
    case_gdc_id                                                       = messages.StringField(8)
    data_category                                                     = messages.StringField(12)
    data_format                                                       = messages.StringField(13)
    data_type                                                         = messages.StringField(14)
    experimental_strategy                                             = messages.StringField(15)    
    index_file_name_key                                               = messages.StringField(19)
    file_name_key                                                     = messages.StringField(18)
    platform                                                          = messages.StringField(20)
    sample_barcode                                                    = messages.StringField(21)
    sample_gdc_id                                                     = messages.StringField(22)
    sample_type                                                       = messages.StringField(23)
    
class Data_HG38MetadataRangesItem(messages.Message):
    access                                                            = messages.StringField(1, repeated=True)
    case_barcode                                                      = messages.StringField(7, repeated=True)
    case_gdc_id                                                       = messages.StringField(8, repeated=True)
    data_category                                                     = messages.StringField(12, repeated=True)
    data_format                                                       = messages.StringField(13, repeated=True)
    data_type                                                         = messages.StringField(14, repeated=True)
    experimental_strategy                                             = messages.StringField(15, repeated=True)
    index_file_name_key                                               = messages.StringField(19, repeated=True)
    file_name_key                                                     = messages.StringField(18, repeated=True)
    platform                                                          = messages.StringField(20, repeated=True)
    sample_barcode                                                    = messages.StringField(21, repeated=True)
    sample_gdc_id                                                     = messages.StringField(22, repeated=True)
    sample_type                                                       = messages.StringField(23, repeated=True)
    
class Data_HG38MetadataItem(messages.Message):
    access                                                            = messages.StringField(1)
    case_barcode                                                      = messages.StringField(7)
    case_gdc_id                                                       = messages.StringField(8)
    data_category                                                     = messages.StringField(12)
    data_format                                                       = messages.StringField(13)
    data_type                                                         = messages.StringField(14)
    experimental_strategy                                             = messages.StringField(15)
    index_file_name_key                                               = messages.StringField(19)
    file_name_key                                                     = messages.StringField(18)
    platform                                                          = messages.StringField(20)
    sample_barcode                                                    = messages.StringField(21)
    sample_gdc_id                                                     = messages.StringField(22)
    sample_type                                                       = messages.StringField(23)
    
class MetadataRangesItem(messages.Message):
    Common = messages.MessageField(CommonMetadataRangesItem, 1)
    Clinical = messages.MessageField(ClinicalMetadataRangesItem, 2)
    Biospecimen = messages.MessageField(BiospecimenMetadataRangesItem, 3)
    Data_HG19 = messages.MessageField(Data_HG19MetadataRangesItem, 4)
    Data_HG38 = messages.MessageField(Data_HG38MetadataRangesItem, 5)

class MetadataItem(messages.Message):
    Common = messages.MessageField(CommonMetadataItem, 1)
    Clinical = messages.MessageField(ClinicalMetadataItem, 2)
    Biospecimen = messages.MessageField(BiospecimenMetadataItem, 3)
    Data_HG19 = messages.MessageField(Data_HG19MetadataItem, 4)
    Data_HG38 = messages.MessageField(Data_HG38MetadataItem, 5)
    
